# Generated by Django 3.1.7 on 2021-05-28 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_userresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userresult',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quizmodel'),
        ),
    ]
