# Generated by Django 3.1.7 on 2021-05-28 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20210528_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userresult',
            name='quiz',
        ),
        migrations.AddField(
            model_name='userresult',
            name='quiz_id',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
